version: '3.4'

services:
  api:
    build: ./src/api
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - mkc-db:/var/lib/mkc-api/data
      - ./src/api/app.py:/usr/src/app/app.py
    networks:
      - backend
      - minio
  frontend:
    build: ./src/frontend
    ports:
      - 8001:8001
    volumes:
      - ./src/frontend:/usr/src/app
    networks:
      - frontend
      - backend
  cf-worker:
    build: ./src/cf-worker
    ports:
      - 5000:5000
  s3-emulator:
    command: server /s3/data --console-address ":9001"
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - mkc-s3:/s3/data
    environment:
      MINIO_ROOT_USER : admin
      MINIO_ROOT_PASSWORD : mkcadmin123
    networks:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mkc-db:
  mkc-s3:

networks:
  frontend:
  backend:
  minio: